Migrate super-mode-calculator from Teamcity to GitHub Actions
guardian/support-analytics pull request #136
Opened 2023-08-09 17:04 UTC by LAKSHMIRPILLAI

## What does this change?

## How to test

## How can we measure success?

## Have we considered potential risks?

## Images

## Accessibility

-   [ ] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#screen-reader)
-   [ ] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-technology/02-physical.md#keyboard)
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#contrast)
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#use-of-colour)

2023-08-10 09:36 UTC, LAKSHMIRPILLAI commented
Deployed the changes to code  via Riff-Raff without issues 

<img width="1449" alt="image" src="https://github.com/guardian/support-analytics/assets/73653255/212d4f39-0474-44dc-b854-9f44d3128588">

2023-08-11 09:30 UTC, undergroundquizscene approved these changes
Looks good :)

2023-08-11 17:13 UTC, akash1810 requested changes

2023-08-11 17:13 UTC, akash1810 commented on .github/workflows/super-mode-calculator.yaml
> +          node-version: 14.16.0
Worth noting https://github.com/guardian/actions-setup-node is deprecated (and archived) in favour of its upstream fork https://github.com/actions/setup-node.

Thoughts on how to make this easier to discover, i.e. reduce the chance/risk of the deprecated action being used, most welcomed.

2023-08-16 09:22 UTC, merged